# 异常处理

## 错误和异常
> 错误：语法错误；
> 异常：语句或表达式的在语法上是正确的，程序执行过程中并不是不会出错的，仍可能出现错误，这个程序运行期间检测到的错误被称为异常。

```
10 * (1/0) 
# ZeroDivisionError: division by zero
4 + spam*3
# NameError: name 'spam' is not defined
'2' + 2
# TypeError: Can't convert 'int' object to str implicitly
```
除如上的被除数为0，变量未定义等外，如抓取数据网络断了、写文件磁盘满了也会产生异常

## 捕获异常的“套路”
```
try:
	# 尝试执行的代码
	pass
except 错误类型1:
	pass
except (错误类型2,错误类型3):
	pass
except Exception as e:
	# 捕获未知错误
	pass
else:
	# 没有异常才会执行的代码
	pass
finally:
	# 无论是否有异常，都会执行的代码（若有异常如果没有被任何except截获，会在finally执行后抛出）
	pass
```

## 异常传递
当函数/方法执行出现异常，如果异常没有被捕获，程序不会立即终止，会将异常传递给调用的一方，如果一直未捕获，就会一直向上传递，如果传递到主程序仍被捕获和处理，最后被Python解释器捕获，打印一个错误信息，程序才会终止。
以下是异常传递的例子
```
def this_fails():
    x = 1 / 0

def main():
    try:
        this_fails()
    except ZeroDivisionError as err:
        print('Handling run-time error:', err)
main()
```

## 抛出异常
使用 `raise` 关键字抛出异常
```
# 抛出异常实例
raise Exception("desc info")
# 抛出异常类 （会使用不带参数的构造函数隐式实例化该异常）
raise ValueError  # shorthand for 'raise ValueError()'
```

捕获的异常可以不处理，然后使用 `raise` 重新抛出该异常或其它异常
```
try:
	raise NameError('HiThere')
except NameError:
	print('An exception flew by!')
	raise
```

## 自定义异常（知识点在面向对象后）
自定义异常，一般用于报告自定义的功能中可能发生的错误。
当创建一个模块有可能抛出多种不同的异常时，一种通常的做法是为这个包建立一个基础异常类，然后基于这个基础类为不同的错误情况创建不同的子类:
```
class Error(Exception):
    """Base class for exceptions in this module."""
    pass

class InputError(Error):
    """Exception raised for errors in the input.

    Attributes:
        expression -- input expression in which the error occurred
        message -- explanation of the error
    """

    def __init__(self, expression, message):
        self.expression = expression
        self.message = message

class TransitionError(Error):
    """Raised when an operation attempts a state transition that's not
    allowed.

    Attributes:
        previous -- state at beginning of transition
        next -- attempted new state
        message -- explanation of why the specific transition is not allowed
    """

    def __init__(self, previous, next, message):
        self.previous = previous
        self.next = next
        self.message = message
```

# 参考文档
1. 官网 [异常](https://docs.python.org/3.5/tutorial/errors.html#exceptions) | [内置异常类型](https://docs.python.org/3.5/library/exceptions.html#bltin-exceptions) | [raise 语句](https://docs.python.org/3.5/reference/simple_stmts.html#raise) | [异常层次结构](https://docs.python.org/3.5/library/exceptions.html#exception-hierarchy)